export const PRODUCTS = [
    {
        id: 1,
        name: 'iPhone 14',
        description: 'The iPhone 14 is a flagship smartphone known for its cutting-edge features and sleek design. With a powerful processor, stunning display, and advanced camera system, it offers a seamless user experience. It is packed with innovative technologies and is a must-have for tech enthusiasts.',
        price: 999.00,
        image: require('../assets/images/iPhone14.png'),
        featured: false,
        category: 'mobile',
        rating: 5,
        inStock: 22,
        fastDelivery: true,
      },
      {
        id: 2,
        name: 'LG Refrigerator',
        description: 'The LG Refrigerator is a high-quality appliance that combines style and functionality. With a spacious capacity and smart cooling features, it provides optimal storage for your food and beverages. Its modern design and energy-efficient performance make it an ideal choice for any kitchen setup. Say goodbye to food wastage and enjoy the convenience of this reliable refrigerator.',
        price: 1200.00,
        image: require('../assets/images/lg27.2CuFtSidebySideRefrigerator.png'),
        featured: true,
        category: 'appliance',
        rating: 2,
        inStock: 15,
        fastDelivery: false,
      },
      {
        id: 3,
        name: 'Senheiser Over Ear Headphones',
        description: 'Experience immersive audio with the Senheiser Over Ear Headphones. These high-quality headphones deliver rich sound and exceptional comfort, making them perfect for music lovers and audiophiles. With their stylish design and advanced features, they offer an unparalleled listening experience.',
        price: 200.00,
        image: require('../assets/images/senheisserHeadphones.jpg'),
        featured: true,
        category: 'accessories',
        rating: 4,
        inStock: 0,
        fastDelivery: true,
      },
      {
        id: 4,
        name: 'Google Pixel 5',
        description: 'Discover the Google Pixel 5, a feature-packed smartphone that offers a premium Android experience. With its powerful camera, smooth performance, and clean software, it provides a seamless user experience. Stay connected and capture stunning photos with this top-notch device.',
        price: 399.00,
        image: require('../assets/images/pixel5.png'),
        featured: false,
        category: 'mobile',
        rating: 3,
        inStock: 3,
        fastDelivery: false,
      },
      {
        id: 5,
        name: 'Macbook Air 2018',
        description: 'The Macbook Air 2018 is a lightweight and powerful laptop that combines performance and portability. With its sleek design, stunning Retina display, and long battery life, it is perfect for both work and entertainment. Experience the power of macOS and enjoy seamless multitasking with this cutting-edge device.',
        price: 599.00,
        image: require('../assets/images/macBookAir.png'),
        featured: true,
        category: 'computing',
        rating: 5,
        inStock: 0,
        fastDelivery: true,
      },
      {
        id: 6,
        name: 'Sony Playstation 5',
        description: 'Looking for the ultimate gaming console? Look no further than the PlayStation 5, released in 2020. With powerful hardware, stunning graphics, and an extensive library of exclusive games, this console is a must-have for any avid gamer.',
        price: 499.99,
        image: require('../assets/images/playStation5.png'),
        featured: true,
        category: 'videogames',
        rating: 5,
        inStock: 22,
        fastDelivery: true,
      },
      {
        id: 7,
        name: 'LG Monitor',
        description: "Enhance your productivity with the LG Monitor. With its high-resolution display and wide viewing angles, it offers a vivid and immersive visual experience. Whether you're working, gaming, or watching movies, this monitor delivers exceptional performance and image quality.",
        price: 219.99,
        image: require('../assets/images/lgMonitor.png'),
        featured: true,
        category: 'computing',
        rating: 2,
        inStock: 2,
        fastDelivery: true,
      },
      {
        id: 12,
        name: 'Apple Watch SE',
        description: 'The Apple Watch SE is a powerful smartwatch with a sleek design. Stay connected, track your fitness, and enjoy a range of features right from your wrist. With its advanced technology and seamless integration with your Apple devices, it is the perfect companion for your everyday life.',
        price: 175.00,
        image: require('../assets/images/appleWatchSE.png'),
        featured: false,
        category: 'accessories',
        rating: 2,
        inStock: 8,
        fastDelivery: true,
      },
      {
        id: 13,
        name: 'Logitech MX Master Mouse',
        description: 'Upgrade your productivity with the Logitech MX Master Mouse. This ergonomic mouse offers precise tracking and customizable controls, allowing you to work more efficiently. With its comfortable design and long battery life, it is perfect for long hours of use.',
        price: 99.96,
        image: require('../assets/images/logitechMXMaster3Mouse.png'),
        featured: false,
        category: 'accessories',
        rating: 4,
        inStock: 23,
        fastDelivery: true,
      },
      {
        id: 14,
        name: 'Samsung Galaxy Fold 4',
        description: 'Experience the future of smartphones with the Samsung Galaxy Fold 4. This cutting-edge device features a foldable display that provides a tablet-like experience in a compact form factor. With its powerful performance and versatile camera system, it is a device that pushes the boundaries of mobile technology.',
        price: 1499.00,
        image: require('../assets/images/samsungGalaxyFold4.png'),
        featured: true,
        category: 'mobile',
        rating: 4,
        inStock: 29,
        fastDelivery: true,
      },
      {
        id: 15,
        name: 'Amana Electric Range',
        description: 'The Amana Electric Range offers a seamless cooking experience with its advanced features and sleek design. With precise temperature control and multiple cooking modes, it allows you to prepare delicious meals with ease. Upgrade your kitchen with this high-quality electric range.',
        price: 1499.00,
        image: require('../assets/images/amanaElectricRange.png'),
        featured: false,
        category: 'appliance',
        rating: 4,
        inStock: 7,
        fastDelivery: false,
      },
      {
        id: 16,
        name: 'Nintendo Switch OLED',
        description: 'The Nintendo Switch OLED is the ultimate gaming console for gamers on the go. With its vibrant OLED display and enhanced audio, it delivers immersive gaming experiences. Play your favorite games anytime, anywhere, and enjoy the versatility of the Switch platform.',
        price: 299.00,
        image: require('../assets/images/nintendoSwitchOled.png'),
        featured: true,
        category: 'videogames',
        rating: 4,
        inStock: 55,
        fastDelivery: true,
      },
      {
        id: 17,
        name: 'Dell XPS 13',
        description: 'The Dell XPS 13 is a high-performance laptop that combines power and portability. With its sleek design and stunning display, it offers an immersive computing experience for work or play.',
        price: 175.00,
        image: require('../assets/images/DellXPS13.png'),
        featured: false,
        category: 'computing',
        rating: 4,
        inStock: 4,
        fastDelivery: true,
      },
      {
        id: 18,
        name: 'Microsoft Surface Pro 9',
        description: "The Microsoft Surface Pro 9 is a versatile 2-in-1 device that adapts to your needs. Whether you're working, creating, or relaxing, it offers the power and flexibility to do it all.",
        price: 799.00,
        image: require('../assets/images/microsoftSurfacePro9.png'),
        featured: false,
        category: 'computing',
        rating: 4,
        inStock: 0,
        fastDelivery: true,
      },
      {
        id: 19,
        name: '24" iMac 4K display',
        description: 'The 24" iMac with 4K display is a stunning all-in-one desktop computer. With its powerful performance and vibrant display, it is perfect for creative professionals and anyone seeking a premium computing experience.',
        price: 1399.00,
        image: require('../assets/images/24iniMac4k.png'),
        featured: true,
        category: 'computing',
        rating: 5,
        inStock: 4,
        fastDelivery: false,
      },
      {
        id: 20,
        name: 'HP Omen 25L Gaming Desktop',
        description: 'The HP Omen 25L Gaming Desktop is a powerful gaming machine designed for performance. With its high-end specifications and sleek design, it delivers an immersive gaming experience.',
        price: 799.00,
        image: require('../assets/images/hpOmen25LGamingDesktop.png'),
        featured: false,
        category: 'computing',
        rating: 1,
        inStock: 20,
        fastDelivery: false,
      },
      {
        id: 21,
        name: 'Motorola RAZR',
        description: 'The Motorola RAZR is a modern take on the classic flip phone. With its sleek design and innovative features, it offers a unique and nostalgic mobile experience.',
        price: 699.00,
        image: require('../assets/images/motorolaRazr2020.png'),
        featured: true,
        category: 'mobile',
        rating: 4,
        inStock: 0,
        fastDelivery: true,
      },
      {
        id: 22,
        name: 'LG - 27.2 Cu Ft Side by Side Refrigerator',
        description: 'The LG 27.2 Cu Ft Side by Side Refrigerator is a spacious and efficient appliance for your kitchen. With its advanced features and stylish design, it keeps your food fresh and organized.',
        price: 174.99,
        image: require('../assets/images/lg27.2CuFtSidebySideRefrigerator.png'),
        featured: false,
        category: 'appliance',
        rating: 1,
        inStock: 1,
        fastDelivery: true,
      },
      {
        id: 23,
        name: 'Insignia - 300 sq. Ft. Portable Air Conditioner',
        description: 'The Insignia Portable Air Conditioner is a convenient solution for cooling small spaces. With its compact design and powerful performance, it provides comfort during hot summer days.',
        price: 599.00,
        image: require('../assets/images/insignia-300sqFtPortableAirConditioner.png'),
        featured: false,
        category: 'appliance',
        rating: 1,
        inStock: 20,
        fastDelivery: false,
      },
      {
        id: 24,
        name: 'Dyson - HP01 Pure Hot+Cool Air Purifier and Fan',
        description: 'The Dyson HP01 Pure Hot+Cool Air Purifier and Fan is a versatile appliance that helps maintain a comfortable and clean environment. With its advanced features, it provides heating, cooling, and air purification all in one.',
        price: 129.99,
        image: require('../assets/images/dyson-HP01PureHot+CoolAirPurifierAndFan.png'),
        featured: false,
        category: 'appliance',
        rating: 1,
        inStock: 12,
        fastDelivery: true,
      },
      {
        id: 25,
        name: 'LG - 4.5 Cu. Ft HE Smart Front Load Washer and Dryer',
        description: 'The LG 4.5 Cu. Ft HE Smart Front Load Washer and Dryer is a high-quality laundry solution. With its smart features and large capacity, it provides efficient and convenient washing and drying for your clothes.',
        price: 899.00,
        image: require('../assets/images/lg27.2CuFtSidebySideRefrigerator.png'),
        featured: false,
        category: 'appliance',
        rating: 4,
        inStock: 15,
        fastDelivery: true,
      },
      {
        id: 26,
        name: 'Xbox Series X',
        description: 'The Xbox Series X is the latest gaming console from Microsoft. With its powerful hardware and extensive game library, it delivers a seamless and immersive gaming experience.',
        price: 499.00,
        image: require('../assets/images/microsoftXboxSeriesX.png'),
        featured: false,
        category: 'videogames',
        rating: 4,
        inStock: 19,
        fastDelivery: false,
      },
      {
        id: 27,
        name: 'Sony Playstation 5 Digital Edition',
        description: 'The Sony Playstation 5 Digital Edition is a digital-only version of the popular gaming console. With its sleek design and impressive performance, it offers a vast selection of digital games and entertainment options.',
        price: 399.00,
        image: require('../assets/images/sonyPlaystation5DigitalEdition.png'),
        featured: false,
        category: 'videogames',
        rating: 4,
        inStock: 9,
        fastDelivery: true,
      },
      {
        id: 28,
        name: 'Nintendo Switch Lite',
        description: 'The Nintendo Switch Lite is a compact and portable gaming console. With its handheld design and extensive game library, it provides a great gaming experience on the go.',
        price: 199.00,
        image: require('../assets/images/nintendoSwitchLite.png'),
        featured: false,
        category: 'videogames',
        rating: 4,
        inStock: 38,
        fastDelivery: false,
      },
      {
        id: 29,
        name: 'Meta Quest 2',
        description: 'The Meta Quest 2 is a virtual reality headset that offers immersive gaming experiences. With its advanced features and wide range of compatible games, it provides a new level of gaming enjoyment.',
        price: 399.00,
        image: require('../assets/images/metaQuest2.png'),
        featured: true,
        category: 'videogames',
        rating: 5,
        inStock: 65,
        fastDelivery: true,
      },
      {
        id: 30,
        name: 'Samsung Galaxy Watch 5',
        description: 'The Samsung Galaxy Watch 5 is a stylish and feature-rich smartwatch. With its advanced health tracking and communication capabilities, it keeps you connected and helps you stay on top of your fitness goals.',
        price: 299.00,
        image: require('../assets/images/samsungGalaxyWatch5.png'),
        featured: false,
        category: 'accessories',
        rating: 3,
        inStock: 14,
        fastDelivery: true,
      },
      {
        id: 31,
        name: 'Apple Airpods Pro',
        description: 'The Apple Airpods Pro is a high-quality wireless earbud option. With its active noise cancellation and superior sound quality, it provides an immersive listening experience.',
        price: 249.99,
        image: require('../assets/images/airpodsPro.png'),
        featured: false,
        category: 'accessories',
        rating: 5,
        inStock: 26,
        fastDelivery: true,
      },
      {
        id: 32,
        name: 'Logitech MX Master Keyboard',
        description: 'The Logitech MX Master Keyboard is a versatile and ergonomic keyboard option. With its comfortable design and customizable features, it enhances your typing experience and productivity.',
        price: 88.88,
        image: require('../assets/images/logitechMXMasterKeyboard.jpg'),
        featured: false,
        category: 'accessories',
        rating: 3,
        inStock: 52,
        fastDelivery: false,
      }
];

