export const PRODUCTS = [
    {
        id: 1,
        name: 'iPhone 14',
        description: 'This is a description for Product 1',
        price: 100,
        image: require('../assets/images/iPhone14.png'),
        featured: false,
        category: 'mobile',
        rating: 3,
        inStock: 22,
        fastDelivery: true,
    },
    {
        id: 2,
        name: 'LG Refrigerator',
        description: 'This is a description for Product 2',
        price: 200,
        image: require('../assets/images/lg27.2CuFtSidebySideRefrigerator.png'),
        featured: true,
        category: 'applicance',
        rating: 2,
        inStock: 15,
        fastDelivery: false,
    },
    {
        id: 3,
        name: 'Senheiser Over Ear Headphones',
        description: 'This is a description for Product 3',
        price: 150,
        image: require('../assets/images/senheisserHeadphones.jpg'),
        featured: true,
        category: 'accessories',
        rating: 4,
        inStock: 0,
        fastDelivery: true,
    },
    {
        id: 4,
        name: 'Google Pixel 5',
        description: 'This is a description for Product 4',
        price: 300,
        image: require('../assets/images/pixel5.png'),
        featured: false,
        category: 'mobile',
        rating: 3,
        inStock: 3,
        fastDelivery: false,
    },
    {
        id: 5,
        name: 'Macbook Air 2018',
        description: 'This is a description for Product 5',
        price: 250,
        image: require('../assets/images/macBookAir.png'),
        featured: true,
        category: 'computing',
        rating: 5,
        inStock: 0,
        fastDelivery: true,
    },
    {
        id: 6,
        name: 'Sony Playstation 5',
        description: 'Looking for the ultimate gaming console? Look no further than the PlayStation 5, released in 2020. With powerful hardware, stunning graphics, and an extensive library of exclusive games, this console is a must-have for any avid gamer.',
        price: 499.99,
        image: require('../assets/images/playStation5.png'),
        featured: true,
        category: 'videogames',
        rating: 5,
        inStock: 22,
        fastDelivery: true,
    },
    {
        id: 7,
        name: 'LG Monitor',
        description: 'This is a description for Product 5',
        price: 250,
        image: require('../assets/images/lgMonitor.png'),
        featured: true,
        category: 'computing',
        rating: 2,
        inStock: 2,
        fastDelivery: true,
    },
    {
        id: 8,
        name: 'Washer Machine',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/lgWasherMachine.png'),
        featured: true,
        category: 'appliance',
        rating: 3,
        inStock: 0,
        fastDelivery: false,
    },
    {
        id: 9,
        name: 'The Legend of Zelda: BOTW ',
        description: 'This is a description for Product 5',
        price: 250,
        image: require('../assets/images/theLengendOfZeldaBOTW.jpg'),
        featured: true,
        category: 'videogames',
        rating: 5,
        inStock: 12,
        fastDelivery: true,
    },
    {
        id: 10,
        name: 'Samsung Galaxy S21',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/samsungGalaxyS23.png'),
        featured: true,
        category: 'mobile',
        rating: 4,
        inStock: 55,
        fastDelivery: true,
    },
    {
        id: 11,
        name: 'iPhone SE 3rd Generation',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/appleiPhoneSE3rdGen.png'),
        featured: false,
        category: 'mobile',
        rating: 3,
        inStock: 4,
        fastDelivery: false,
    },
    {
        id: 12,
        name: 'Apple Watch SE',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/appleWatchSE.png'),
        featured: false,
        category: 'accessories',
        rating: 2,
        inStock: 8,
        fastDelivery: true,
    },
    {
        id: 13,
        name: 'Logitech MX Master Mouse',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/logitechMXMaster3Mouse.png'),
        featured: false,
        category: 'accessories',
        rating: 4,
        inStock: 23,
        fastDelivery: true,
    },
    {
        id: 14,
        name: 'Samsung Galaxy Fold 4',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/samsungGalaxyFold4.png'),
        featured: true,
        category: 'mobile',
        rating: 3,
        inStock: 29,
        fastDelivery: true,
    },
    {
        id: 15,
        name: 'Amana Electric Range',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/amanaElectricRange.png'),
        featured: false,
        category: 'appliance',
        rating: 4,
        inStock: 7,
        fastDelivery: false,
    },
    {
        id: 16,
        name: 'Nintendo Switch OLED',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/nintendoSwitchOled.png'),
        featured: true,
        category: 'videogames',
        rating: 4,
        inStock: 55,
        fastDelivery: true,
    },
    {
        id: 17,
        name: 'Dell XPS 13',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/DellXPS13.png'),
        featured: false,
        category: 'computing',
        rating: 4,
        inStock: 4,
        fastDelivery: true,
    },
    {
        id: 18,
        name: 'Microsoft Surface Pro 9',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/microsoftSurfacePro9.png'),
        featured: false,
        category: 'computing',
        rating: 4,
        inStock: 0,
        fastDelivery: true,
    },
    {
        id: 19,
        name: '24" iMac 4K display',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/24iniMac4k.png'),
        featured: true,
        category: 'computing',
        rating: 5,
        inStock: 4,
        fastDelivery: false,
    },
    {
        id: 20,
        name: 'HP Omen 25L Gaming Desktop',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/hpOmen25LGamingDesktop.png'),
        featured: false,
        category: 'computing',
        rating: 1,
        inStock: 20,
        fastDelivery: false,
    },
    {
        id: 21,
        name: 'Motorola RAZR',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/motorolaRazr2020.png'),
        featured: true,
        category: 'mobile',
        rating: 3,
        inStock: 0,
        fastDelivery: true,
    },
    {
        id: 22,
        name: 'LG - 27.2 Cu Ft Side by Side Refrigerator',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/lg27.2CuFtSidebySideRefrigerator.png'),
        featured: false,
        category: 'appliance',
        rating: 1,
        inStock: 1,
        fastDelivery: true,
    },
    {
        id: 23,
        name: 'Insignia - 300 sq. Ft. Portable Air Conditioner',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/insignia-300sqFtPortableAirConditioner.png'),
        featured: false,
        category: 'appliance',
        rating: 1,
        inStock: 20,
        fastDelivery: false,
    },
    {
        id: 24,
        name: 'Dyson - HP01 Pure Hot+Cool Air Purifier and Fan',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/dyson-HP01PureHot+CoolAirPurifierAndFan.png'),
        featured: false,
        category: 'appliance',
        rating: 1,
        inStock: 12,
        fastDelivery: true,
    },
    {
        id: 25,
        name: 'LG - 4.5 Cu. Ft HE Smart Front Load Washer and Dryer',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/lg4.5CuFt HESmartFrontLoadWasherAndDryer.png'),
        featured: false,
        category: 'appliance',
        rating: 4,
        inStock: 15,
        fastDelivery: true,
    },
    {
        id: 26,
        name: 'Xbox Series X',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/microsoftXboxSeriesX.png'),
        featured: false,
        category: 'videogames',
        rating: 4,
        inStock: 19,
        fastDelivery: false,
    },
    {
        id: 27,
        name: 'Sony Playstation 5 Digital Edition',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/sonyPlaystation5DigitalEdition.png'),
        featured: false,
        category: 'videogames',
        rating: 4,
        inStock: 9,
        fastDelivery: true,
    },
    {
        id: 28,
        name: 'Nintendo Switch Lite',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/nintendoSwitchLite.png'),
        featured: false,
        category: 'videogames',
        rating: 4,
        inStock: 38,
        fastDelivery: false,
    },
    {
        id: 29,
        name: 'Meta Quest 2',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/metaQuest2.png'),
        featured: true,
        category: 'videogames',
        rating: 5,
        inStock: 65,
        fastDelivery: true,
    },

    {
        id: 30,
        name: 'Samsung Galaxy Watch 5',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/samsungGalaxyWatch5.png'),
        featured: false,
        category: 'accessories',
        rating: 3,
        inStock: 14,
        fastDelivery: true,
    },
    {
        id: 31,
        name: 'Apple Airpods Pro',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/airpodsPro.png'),
        featured: false,
        category: 'accessories',
        rating: 5,
        inStock: 26,
        fastDelivery: true,
    },
    {
        id: 32,
        name: 'Logitech MX Master Keyboard',
        description: 'This is a description for Product 6',
        price: 175,
        image: require('../assets/images/logitechMXMasterKeyboard.jpg'),
        featured: false,
        category: 'accessories',
        rating: 3,
        inStock: 52,
        fastDelivery: false,
    }
];

